# Generated by Django 5.0.3 on 2024-04-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ide_user',
            new_name='id_user',
        ),
    ]
